---
- name: Deploy Application
  hosts: all
  become: yes

  vars_prompt:
    - name: "username"
      prompt: "Enter the username: "
      private: no

    - name: "appname"
      prompt: "Enter application name: "
      private: no

    - name: "url"
      prompt: "Enter URL to download application package: "
      private: no

  tasks:
    - name: Create new user
      user:
        name: "{{ username }}"
        state: present

    - name: Download application package
      get_url:
        url: "{{ url }}"
        dest: "/home/{{ username }}/{{ appname }}.tar.gz"

    - name: Extract application package
      unarchive:
        src: "/home/{{ username }}/{{ appname }}.tar.gz"
        dest: "/home/{{ username }}/{{ appname }}"
        remote_src: yes

    - name: Start application
      command: "/home/{{ username }}/{{ appname }}/{{ appname }}.sh &"
